[package]
name = "storekey-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.93"
aes-gcm = "0.10.3"
base64 = "0.22.1"
clap = { version = "4.5.21", features = ["derive"] }
sha3 = "0.10.8"
